name: CI - Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t automation-tests_with_pytest_fw .

    - name: Run tests_with_pytest_fw in Docker container
      run: docker run --name test-runner automation-tests_with_pytest_fw

    - name: Copy test reports from container
      run: |
        docker cp test-runner:/app/html-report ./html-report || echo "No HTML report"
        docker cp test-runner:/app/allure-report ./allure-report || echo "No Allure report"

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: html-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Clean up Docker container
      run: docker rm test-runner