name: Run Tests in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry (optional)
      if: false  # включи, если пушишь образ
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t playwright-tests .

    - name: Run tests in Docker with mounted allure-results
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/allure-results:/app/allure-results \
          playwright-tests

    - name: Generate Allure Report
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/allure-results:/app/allure-results \
          -v ${{ github.workspace }}/allure-report:/app/allure-report \
          frankescobar/allure-docker-service generate \
          /app/allure-results -o /app/allure-report --clean
    
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report

